#!/usr/bin/env perl

=head1 NAME

osc52 - Implement OSC 52; Interact with X11 clipboard

=head1 SYNOPSIS

   urxvt -pe osc52

=head1 DESCRIPTION

This extension implements OSC 52 for interacting with system clipboard

Most code stolen from:
http://ailin.tucana.uberspace.de/static/nei/*/Code/urxvt/

=cut

use MIME::Base64;
use Encode;

sub on_osc_seq {
    my ($term, $op, $args) = @_;
    return () unless $op eq 52;

    my ($clip, $data) = split ';', $args, 2;
    if ($data eq '?') {
        my $data_free = $term->selection();
        Encode::_utf8_off($data_free); # XXX
        $term->tt_write("\e]52;$clip;".encode_base64($data_free, '')."\a");
    }
    else {
        my $data_decoded = decode_base64($data);
        Encode::_utf8_on($data_decoded); # XXX
        $term->selection($data_decoded, 1);
        $term->selection_grab(urxvt::CurrentTime, 1);
        $term->selection($data_decoded);
        $term->selection_grab(urxvt::CurrentTime);
    }

    ()
}
