#!/usr/bin/env zsh

set -eo pipefail
export PATH=$HOME/.ghcup/bin:$PATH

cabal build xmobar-local
bin=$(jq -r '.["install-plan"][] | select(.["pkg-name"] == "xmobar-local").components["exe:xmobar-local"]["bin-file"]' dist-newstyle/cache/plan.json)

if [[ ! -a $1 || "$(stat -c '%i' $bin)" != "$(stat -c '%i' $1)" ]]; then
  strip $bin
  ln -f $(realpath --relative-to=. $bin) $1
fi
