#!/usr/bin/env zsh

cfg=xmobar.hs
[[ $1 -nt $cfg ]] && exit

export PATH=$HOME/.ghcup/bin:$PATH
exec cabal exec ghc -- \
  --make $cfg \
  -package xmobar \
  -i -ilib \
  -fforce-recomp \
  -main-is main \
  -v0 \
  -o "$1"
